# Uncomment the next line to define a global platform for your project
platform :ios, ‘7.0’
pod 'ASOAnimatedButton'

target 'Github_lesson_1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Github_lesson_1

end
